### ISSUE TITLE
Version Constraint Overly-Restrictive for Git Builds

### ISSUE THREAD

**Issue by theory** [theory/pgenv#75]
To support building from the Git repository using `PGENV_LOCAL_POSTGRESQL_REPO`, it'd be nice to allow arbitrary version numbers or tags, so that one can build multiple configurations and just give them different names. As it is, one might find it difficult to figure out what's acceptable and what's not.

So maybe we could avoid checking the version when building from Git, or maybe compare the version in Git? Might be nice to allow using a branch name, too.

**Comment by fluca1978** [comment]
At glance, we could play with `v` to keep the git tag/HEAD and avoid exiting when checking the PostgreSQL version number.
But quite frankly, I think this could introduce too much workarounds for handling special cases and variable combinations.

I would prefer to refactor the commands so that we have:
- `pgenv build 16.1`
- `pgenv git build HEAD`

so introducing the new command `git` that accepts `build` and `rebuild` and surely knows we are going to build out of a git repository. But this is going to break retro-compatibility.

**Comment by theory** [comment]
Seems like a good idea. How would it break compatibility?

**Comment by fluca1978** [comment]
> Seems like a good idea. How would it break compatibility?

At glance, doing `pgenv build latest` with `PGENV_LOCAL_POSTGRESQL_REPO` will not work anymore, since git based builds should be done with `pgenv git build latest`.

**Comment by theory** [comment]
Well maybe that can still work as it did before, when `PGENV_LOCAL_POSTGRESQL_REPO` is set?

If not, doesn't seem like a big deal to suggest that people switch. I doubt many use `PGENV_LOCAL_POSTGRESQL_REPO` so far.

@JelteF, I spend this issue after I saw your comments elsewhere. What do you think?

**Comment by JelteF** [comment]
Keep in mind that I also want to test multiple dev-postgres versions, that are checked out different directories (using `git worktree`). This is useful when I want to cherry-pick a change back to previous versions. So `PGENV_LOCAL_POSTGRESQL_REPO` actually would not be very helpful here if you can only provide a specific directory (unless it also understands git worktrees, which is probably not even that hard since `git worktree list` shows all of them).

**Comment by theory** [comment]
Right, I think we can start with commands succeeding if the directory for the specified version exists, regardless of whether or not it's a known version. I think we only need to be strict with the `build` command.

**Comment by fluca1978** [comment]
If I get it right, the idea is that `pgenv build foo` should understand that `foo` is not  a valid PostgreSQL version and, if `PGENV_LOCAL_POSTGRESQL_REPO` is set, should try to checkout `foo` and build.
Is it right? If so, the check for a PostgreSQL version is allowed to fail iff there is chance to build from git.

**Comment by theory** [comment]
I think that could be useful, yes, but even if we just start with allowing a version in `use` and friends _if the directory with that version name already exists_. That would allow people to build their own clusters named `~/.pgenv/pgsql-whatever/` to use `pgenv use whatever` and have it work.

**Comment by fluca1978** [comment]
Ok  so I'm working on `use` for now. Let me see if this workflow could be fine:


```
% mv ~/git/pgenv/pgsql-17beta1 ~/git/pgenv/pgsql-fluca   # for testing
% pgenv versions
Using PGENV_ROOT /home/luca/git/pgenv
      16.0      pgsql-16.0
      16.1      pgsql-16.1
      16.2      pgsql-16.2
      fluca     pgsql-fluca


% pgenv use fluca
Using PGENV_ROOT /home/luca/git/pgenv
[DEBUG] Guessed PostgreSQL version is [fluca]
[DEBUG] Using externally managed version [fluca] within [pgsql-fluca]   # <- note this new line
...


% pgenv versions
      16.0      pgsql-16.0
      16.1      pgsql-16.1
      16.2      pgsql-16.2
  *   fluca     pgsql-fluca

````


The idea is this: ~pgenv_installed_version_or_exit` will accept another argument that tells to *not exit* if a version does not like an ordinary version but it is found on disk (assuming the format `pgsql-VERSION`). Therefore, all the commands will suddenly work with *externally managed versions* where the user created the directory layout as `pgsql-VERSION`.
Since ~pgenv start` and `pgenv stop` work on the linked directory, not on a version, the whole is transparent.

Is this a good starting point?

**Comment by theory** [comment]
Yeah, that sounds great!

**Comment by JelteF** [comment]
I guess it would be nice if it could detect the major version if it was prefixed with one, so that it could use the same pgdata directory.

**Comment by fluca1978** [comment]
> I guess it would be nice if it could detect the major version if it was prefixed with one, so that it could use the same pgdata directory.

Wait, are we doing this? I don't think so: every installation has its own PGDATA. so `16.1` and `16.2` are noi going to share teh pgdata.
Seems to me you are asking more for grouping installations, so that "all the 16" use the same pgdata, and the "git checkout x, y ,z" use the same pgdata but postgreql 17 will use its own. Am I right?

**Comment by theory** [comment]
Yeah, each of our installs has its own pgdata, but it's configurable with the `PG_DATA` environment variable.

https://github.com/theory/pgenv/blob/02ec3df98da14d532b84e701ee64419f1102b8b9/bin/pgenv#L924-L928

**Comment by JelteF** [comment]
hmm, sorry about that. Somehow I thought it shared pgdata per major version. But you're totally right, that's not the case.

**Comment by fluca1978** [comment]
@theory PTAL at #77 
@JelteF does #77 sounds good for you at this point?

**Comment by fluca1978** [comment]
Since #77 has been merged, and there is no other comment, can we close this issue?

**Comment by theory** [comment]
WFM, yes, thank you, @fluca1978!
